// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaWHt3vEe87LRc3yNzaT_xcDUt1kL1IQ4',
    appId: '1:595660528117:web:0ab63076d1a6c6ecfda8bc',
    messagingSenderId: '595660528117',
    projectId: 'my-horario-u',
    authDomain: 'my-horario-u.firebaseapp.com',
    storageBucket: 'my-horario-u.firebasestorage.app',
    measurementId: 'G-03YYRW8ZXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARCHKtcKIEB0aUdR8DtDZfymx_iXYwCUc',
    appId: '1:595660528117:android:87d9ad7d06f9789cfda8bc',
    messagingSenderId: '595660528117',
    projectId: 'my-horario-u',
    storageBucket: 'my-horario-u.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFJaJkXxw37qpLVUCPypKwqCnDY33mT_s',
    appId: '1:595660528117:ios:04ef16797e9e2ae5fda8bc',
    messagingSenderId: '595660528117',
    projectId: 'my-horario-u',
    storageBucket: 'my-horario-u.firebasestorage.app',
    androidClientId: '595660528117-fg6k0bl4go6fbbdsclrfo1gek309aboh.apps.googleusercontent.com',
    iosClientId: '595660528117-ujjv9i7rbtraaon5mr2br57ho44dhmb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHorariou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFJaJkXxw37qpLVUCPypKwqCnDY33mT_s',
    appId: '1:595660528117:ios:04ef16797e9e2ae5fda8bc',
    messagingSenderId: '595660528117',
    projectId: 'my-horario-u',
    storageBucket: 'my-horario-u.firebasestorage.app',
    androidClientId: '595660528117-fg6k0bl4go6fbbdsclrfo1gek309aboh.apps.googleusercontent.com',
    iosClientId: '595660528117-ujjv9i7rbtraaon5mr2br57ho44dhmb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myHorariou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaWHt3vEe87LRc3yNzaT_xcDUt1kL1IQ4',
    appId: '1:595660528117:web:d9cb1ba5d8db938bfda8bc',
    messagingSenderId: '595660528117',
    projectId: 'my-horario-u',
    authDomain: 'my-horario-u.firebaseapp.com',
    storageBucket: 'my-horario-u.firebasestorage.app',
    measurementId: 'G-W1NV60WP4D',
  );

}